//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Eagleeye2_Viewer.rc
//
#define IDSAVEPARAM                     3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EAGLEETYPE                  129
#define IDD_SELECTFILE_PREVIEW          130
#define IDB_TOOLBAR_DISABLE             131
#define IDB_TOOLBAR_ENABLE              132
#define IDD_TARGETIPADDRESS             133
#define IDD_NEWIPMACSET                 134
#define IDD_NEWIPSET                    134
#define IDD_AFECONFIGDLG                135
#define IDD_AFEGAINCONFIGDLG            135
#define IDD_WHITEBALANCEDLG             136
#define IDD_GIODLG                      137
#define IDD_TRGMODECONFIG               138
#define IDD_MJPEGCONFIG                 139
#define IDD_HFRMODECONFIG               140
#define IDD_AUTOMODECONFIG              141
#define IDD_RTCDLG                      142
#define IDD_WDTDLG                      143
#define IDD_MACCFGDLG                   144
#define IDD_HFRBINMODECONFIG            145
#define IDS_PREVIEW                     1000
#define IDC_TARGETIPADDRESS             1001
#define IDC_NEWIPADDRESS                1002
#define IDC_AFEVGAGAIN                  1004
#define IDC_SHPDSFUNITS                 1008
#define IDC_PORT1IN                     1012
#define IDC_PORT1OUT                    1013
#define IDC_PORT1OUTVALUE               1014
#define IDC_PORT2IN                     1015
#define IDC_TRGSHUTTERTIME              1015
#define IDC_PORT2OUT                    1016
#define IDC_RGBARRAY                    1016
#define IDC_CURTRGSHUTTERTIME           1016
#define IDC_PORT2OUTVALUE               1017
#define IDC_BAYERARRAY                  1017
#define IDC_PORT3IN                     1018
#define IDC_JPEGRAWDATA                 1018
#define IDC_PORT3OUT                    1019
#define IDC_MANUAL                      1019
#define IDC_PORT3OUTVALUE               1020
#define IDC_AUTO                        1020
#define IDC_PORT4IN                     1021
#define IDC_MJPEGSHUTTERTIME            1021
#define IDC_PORT4OUT                    1022
#define IDC_AUTOSHUTTERUPLIMIT          1022
#define IDC_PORT4OUTVALUE               1023
#define IDC_PGAUPLIMIT                  1023
#define IDC_PORT5IN                     1024
#define IDC_HFRSHUTTERTIME              1024
#define IDC_PORT5OUT                    1025
#define IDC_AMCSHUTTERTIMEUPLIMIT       1025
#define IDC_PORT5OUTVALUE               1026
#define IDC_AMCPGAUPLIMIT               1026
#define IDC_PORT6IN                     1027
#define IDC_AMCADJINTERVAL              1027
#define IDC_PORT6OUT                    1028
#define IDC_LEFT                        1028
#define IDC_PORT6OUTVALUE               1029
#define IDC_RIGHT                       1029
#define IDC_PORT7IN                     1030
#define IDC_WBDAYLIGHT                  1030
#define IDC_PORT7OUT                    1031
#define IDC_WBFLUORESCENCE              1031
#define IDC_PORT7OUTVALUE               1032
#define IDC_ORGDATA                     1032
#define IDC_PORT8IN                     1033
#define IDC_PORT8OUT                    1034
#define IDC_PORT8OUTVALUE               1035
#define IDC_PORT9IN                     1036
#define IDC_PORT9OUT                    1037
#define IDC_PORT9OUTVALUE               1038
#define IDC_PORT10IN                    1039
#define IDC_PORT10OUT                   1040
#define IDC_PORT10OUTVALUE              1041
#define IDC_FLASHSYNDISABLE             1042
#define IDC_FLASHSYNENABLE              1043
#define IDC_MEANBRIGHTNESS              1044
#define IDC_RTCYEAR                     1053
#define IDC_RTCMONTH                    1054
#define IDC_RTCDAY                      1055
#define IDC_RTCWEEK                     1056
#define IDC_RTCHOUR                     1057
#define IDC_RTCMINUTE                   1058
#define IDC_RTCSECOND                   1059
#define IDC_WDTENABLE                   1060
#define IDC_WDT                         1061
#define IDC_MACADD1                     1062
#define IDC_SHD                         1062
#define IDC_MACADD2                     1063
#define IDC_RGS                         1063
#define IDC_LOCATION                    1063
#define IDC_MACADD3                     1064
#define IDC_RGE                         1064
#define IDC_SINGALCOIN                  1064
#define IDC_MACADD4                     1065
#define IDC_CDSGAIN                     1065
#define IDC_DOUBLECOIN                  1065
#define IDC_MACADD5                     1066
#define IDC_PXGA0                       1066
#define IDC_INTERVAL                    1066
#define IDC_MACADD6                     1067
#define IDC_PXGA1                       1067
#define IDC_WAYNUM                      1067
#define IDC_PXGA2                       1068
#define IDC_PXGA3                       1069
#define IDC_DOUTPHASE                   1070
#define IDC_SHUTPGAMANUALCTRL           1070
#define IDC_TRGPGA                      1071
#define IDC_SHUTPGAAUTOCTRL             1072
#define IDC_SHUTLIMIT                   1073
#define IDC_PGALIMIT                    1074
#define IDC_SROW                        1075
#define IDC_SCOL                        1076
#define IDC_EROW                        1077
#define IDC_ECOL                        1078
#define IDC_EYMEAN                      1079
#define IDC_ADLIP                       1080
#define IDC_CHECK1                      1081
#define IDC_CURTRGPGA                   1081
#define IDC_ENABLEADLI                  1082
#define IDC_HFRBINSHUTTERTIME           1083
#define ID_OMC_HFRBIN                   4638
#define ID_CONFIG_TARGETIP              32771
#define ID_RUNMODE_OPENMODE             32773
#define ID_RUNMODE_AUTOMODE             32774
#define ID_OMC_TRIGGER                  32775
#define ID_OMC_MJPEG                    32776
#define ID_OMC_HFR                      32777
#define ID_CONIFG_AMC                   32778
#define ID_TRGMODE_CONFIG               32779
#define ID_MJPEGMODE_CONFIG             32780
#define ID_HFRMODE_CONFIG               32781
#define ID_CONFIG_WHITEBALANCE          32782
#define ID_CONFIG_AFECTRL               32783
#define ID_CONFIG_AFEGAINCTRL           32783
#define ID_CONFIG_NEWIPMAC              32784
#define ID_CONFIG_NEWIP                 32784
#define ID_CONFIG_GIOCONFIG             32785
#define ID_OPE_GRAB                     32787
#define ID_OPE_AUTOWB                   32788
#define ID_OPE_RESETSYS                 32789
#define ID_OPE_RELAY_CLOSE              32790
#define ID_OPE_RELAY_OPEN               32791
#define ID_OPE_REMOTEUPDATE             32792
#define ID_OPE_REMOTEUPDATEDSPPRROM     32792
#define ID_CONFIG_RTCCONFIG             32793
#define ID_CONFIG_WDTCONFIG             32794
#define ID_CONFIG_NEWMAC                32795
#define ID_OPE_LUT_ENABLE               32797
#define ID_OPE_LUT_DISABLE              32798
#define ID_OPE_AUTOTRG_ENABLE           32799
#define ID_OPE_AUTOTRG_DISABLE          32800
#define ID_OPE_IMGFORMAT_RGB            32801
#define ID_OPE_IMGFORMAT_YUV            32802
#define ID_OPE_IMGFORMAT_BAYER          32803
#define ID_OPE_TRGSHUTTERCTRL_MANUAL    32804
#define ID_OPE_TRGSHUTTERCTRL_AUTO      32805
#define ID_OMC_HFRB                     32806
#define ID_HFRBINMODE_CONFIG            32807
#define ID_INDICATOR_TEMP               59142
#define IDS_PICFORMAT                   61896
#define ID_INDICATOR_FRAMERATE          61897

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
