
#ifndef _TEST_BCG_INL_
#define _TEST_BCG_INL_
sys_t** psys=0;
#include "bcg.h"
//#include "BCGPButton.h"
#include "Bcgglobals.h"

#include "BCGPGlobalUtils.h"
//#include "BCGPToolBarImages.h"
#include "BCGDraw.inl"
#include "BCGPDrawManager.inl"
#include "BCGPVisualManager.h"
#include "BCGPVisualManager.inl"
#include "BCGPButton.h"
#include "BCGPCalculator.inl"
#if 0
#include "BCGPCalendarBar.inl"
#include "BCGPCalendarMenuButton.inl"

#include "BCGPMenuButton.h"
#include "BCGPControlRenderer.h"
#include "BCGPControlRenderer.inl"
#include "BCGPGlobalUtils.inl"
#include "BCGPVisualManager2003.inl"
#include "BCGPVisualManager2007.inl"
#include "BCGPVisualManagerCarbon.inl"
#include "BCGPVisualManagerScenic.inl"
#include "BCGPVisualManagerVS2005.inl"
#include "BCGPVisualManagerVS2008.inl"
#include "BCGPVisualManagerXP.inl"

#include "BCGPAnimCtrl.inl"
#include "BCGPAppBarWnd.inl"
#include "BCGPAppointment.inl"
#include "BCGPAppointmentDS.inl"
#include "BCGPAppointmentProperty.inl"
#include "BCGPAppointmentStorage.inl"
#include "BCGPAutoHideButton.inl"
#include "BCGPAutoHideDockBar.inl"
#include "BCGPAutoHideToolBar.inl"
#include "BCGPBarContainer.inl"
#include "BCGPBarContainerManager.inl"
#include "BCGPBaseControlBar.inl"
#include "BCGPBaseRibbonElement.inl"
#include "BCGPBaseTabbedBar.inl"
#include "BCGPBaseTabWnd.inl"
#include "BCGPBaseToolBar.inl"
#include "BCGPCaptionBar.inl"
#include "BCGPCaptionButton.inl"
#include "BCGPCaptionMenuButton.inl"
#include "BCGPColorBar.inl"
#include "BCGPColorButton.inl"
#include "BCGPColorDialog.inl"
#include "BCGPColorMenuButton.inl"
#include "BCGPComboBox.inl"
#include "BCGPCommandManager.inl"
#include "BCGPContextMenuManager.inl"
#include "BCGPControlBar.inl"
#include "BCGPControlBarImpl.inl"
#include "BCGPControlRenderer.inl"
#include "BCGPCustomizeMenuButton.inl"
#include "BCGPDAOGridCtrl.inl"
#include "BCGPDateTimeCtrl.inl"
#include "BCGPDBGridCtrl.inl"
#include "BCGPDialog.inl"
#include "BCGPDialogBar.inl"
#include "BCGPDlgImpl.inl"
#include "BCGPDockBar.inl"
#include "BCGPDockBarRow.inl"
#include "BCGPDockingCBWrapper.inl"
#include "BCGPDockingControlBar.inl"
#include "BCGPDockManager.inl"
#include "BCGPDragFrameImpl.inl"
#include "BCGPDrawManager.inl"
#include "BCGPDropDown.inl"
#include "BCGPDropDownList.inl"
#include "BCGPDurationCtrl.inl"
#include "BCGPEdit.inl"
#include "BCGPEditCtrl.inl"
#include "BCGPEditListBox.inl"
#include "BCGPEditView.inl"
#include "BCGPExCheckList.inl"
#include "BCGPExplorerToolBar.inl"
#include "BCGPFileDialog.inl"
#include "BCGPFontComboBox.inl"
#include "BCGPFormView.inl"
#include "BCGPFrameImpl.inl"
#include "BCGPFrameWnd.inl"
#include "BCGPFullScreenImpl.inl"
#include "BCGPGanttChart.inl"
#include "BCGPGanttControl.inl"
#include "BCGPGanttGrid.inl"
#include "BCGPGanttItem.inl"
#include "BCGPGanttItemStorage.inl"
#include "BCGPGanttRenderer.inl"
#include "BCGPGanttView.inl"
#include "BCGPGlobalUtils.inl"
#include "BCGPGridCtrl.inl"
#include "BCGPGridView.inl"
#include "BCGPGroup.inl"
#include "BCGPHeaderCtrl.inl"
#include "BCGPHotSpotImageCtrl.inl"
#include "BCGPImageEditDlg.inl"
#include "BCGPInplaceEdit.inl"
#include "BCGPInplaceToolTipCtrl.inl"
#include "BCGPIntelliSenseLB.inl"
#include "BCGPIntelliSenseWnd.inl"
#include "BCGPKeyboardManager.inl"
#include "BCGPKeyboardPage.inl"
#include "BCGPKeyHelper.inl"
#include "BCGPKeyMapDlg.inl"
#include "BCGPListBox.inl"
#include "BCGPListCtrl.inl"
#include "BCGPLocalRes.inl"
#include "BCGPMainClientAreaWnd.inl"
#include "BCGPMaskEdit.inl"
#include "BCGPMDIChildWnd.inl"
#include "BCGPMDIFrameWnd.inl"
#include "BCGPMenuBar.inl"
#include "BCGPMenuButton.inl"
#include "BCGPMenuPage.inl"
#include "BCGPMessageBox.inl"
#include "BCGPMiniFrameWnd.inl"
#include "BCGPMouseManager.inl"
#include "BCGPMousePage.inl"
#include "BCGPMultiMiniFrameWnd.inl"
#include "BCGPODBCGridCtrl.inl"
#include "BCGPOleCntrFrameWnd.inl"
#include "BCGPOleDocIPFrameWnd.inl"
#include "BCGPOleIPFrameWnd.inl"
#include "BCGPOleServerDoc.inl"
#include "BCGPOptionsPage.inl"
#include "BCGPOutlineParser.inl"
#include "BCGPOutlookBar.inl"
#include "BCGPOutlookBarDockingPane.inl"
#include "BCGPOutlookBarPane.inl"
#include "BCGPOutlookButton.inl"
#include "BCGPOutlookWnd.inl"
#include "BCGPPlannerClockIcons.inl"
#include "BCGPPlannerDropSource.inl"
#include "BCGPPlannerDropTarget.inl"
#include "BCGPPlannerManagerCtrl.inl"
#include "BCGPPlannerManagerView.inl"
#include "BCGPPlannerPrint.inl"
#include "BCGPPlannerPrintDay.inl"
#include "BCGPPlannerPrintDual.inl"
#include "BCGPPlannerPrintMonth.inl"
#include "BCGPPlannerPrintWeek.inl"
#include "BCGPPlannerView.inl"
#include "BCGPPlannerViewDay.inl"
#include "BCGPPlannerViewMonth.inl"
#include "BCGPPlannerViewMulti.inl"
#include "BCGPPlannerViewWeek.inl"
#include "BCGPPlannerViewWorkWeek.inl"
#include "BCGPPngImage.inl"
#include "BCGPPopupDlg.inl"
#include "BCGPPopupMenu.inl"
#include "BCGPPopupMenuBar.inl"
#include "BCGPPopupWindow.inl"
#include "BCGPPowerColorPicker.inl"
#include "BCGPPrintPreviewView.inl"
#include "BCGPProgressCtrl.inl"
#include "BCGPProgressDlg.inl"
#include "BCGPPropertyPage.inl"
#include "BCGPPropertySheet.inl"
#include "BCGPPropList.inl"
#include "BCGPReBar.inl"
#include "BCGPRebarState.inl"
#include "BCGPRecentDockInfo.inl"
#include "BCGPRecurrence.inl"
#include "BCGPRecurrenceRule.inl"
#include "BCGPRecurrenceRules.inl"
#include "BCGPRegistry.inl"
#include "BCGPReportCtrl.inl"
#include "BCGPReportView.inl"
#include "BCGPRibbonBar.inl"
#include "BCGPRibbonButton.inl"
#include "BCGPRibbonButtonsGroup.inl"
#include "BCGPRibbonCategory.inl"
#include "BCGPRibbonCheckBox.inl"
#include "BCGPRibbonCollector.inl"
#include "BCGPRibbonColorButton.inl"
#include "BCGPRibbonComboBox.inl"
#include "BCGPRibbonCommandsListBox.inl"
#include "BCGPRibbonConstructor.inl"
#include "BCGPRibbonCustomizePage.inl"
#include "BCGPRibbonDialogBar.inl"
#include "BCGPRibbonEdit.inl"
#include "BCGPRibbonFloaty.inl"
#include "BCGPRibbonHyperlink.inl"
#include "BCGPRibbonInfo.inl"
#include "BCGPRibbonInfoLoader.inl"
#include "BCGPRibbonInfoWriter.inl"
#include "BCGPRibbonKeyboardCustomizeDlg.inl"
#include "BCGPRibbonKeyTip.inl"
#include "BCGPRibbonLabel.inl"
#include "BCGPRibbonMainPanel.inl"
#include "BCGPRibbonPaletteButton.inl"
#include "BCGPRibbonPanel.inl"
#include "BCGPRibbonPanelMenu.inl"
#include "BCGPRibbonProgressBar.inl"
#include "BCGPRibbonQuickAccessToolbar.inl"
#include "BCGPRibbonSlider.inl"
#include "BCGPRibbonStatusBar.inl"
#include "BCGPRibbonStatusBarPane.inl"
#include "BCGPRibbonUndoButton.inl"
#include "BCGPScrollBar.inl"
#include "BCGPSDPlaceMarkerWnd.inl"
#include "BCGPSelectSkinDlg.inl"
#include "BCGPShellList.inl"
#include "BCGPShellManager.inl"
#include "BCGPShellTree.inl"
#include "BCGPShowAllButton.inl"
#include "BCGPSkinManager.inl"
#include "BCGPSlider.inl"
#include "BCGPSliderCtrl.inl"
#include "BCGPSmartDockingManager.inl"
#include "BCGPSmartDockingMarker.inl"
#include "BCGPSound.inl"
#include "BCGPSpinButtonCtrl.inl"
#include "BCGPSplitterWnd.inl"
#include "BCGPStatic.inl"
#include "BCGPStatusBar.inl"
#include "BCGPTabbedControlBar.inl"
#include "BCGPTabbedToolbar.inl"
#include "BCGPTabView.inl"
#include "BCGPTabWnd.inl"
#include "BCGPTagManager.inl"
#include "BCGPTaskPaneMiniFrameWnd.inl"
#include "BCGPTasksPane.inl"
#include "BCGPTearOffManager.inl"
#include "BCGPToolBar.inl"
#include "BCGPToolbarButton.inl"
#include "BCGPToolbarComboBoxButton.inl"
#include "BCGPToolbarCustomize.inl"
#include "BCGPToolbarCustomizePages.inl"
#include "BCGPToolbarDateTimeCtrl.inl"
#include "BCGPToolbarDropSource.inl"
#include "BCGPToolbarDropTarget.inl"
#include "BCGPToolbarEditBoxButton.inl"
#include "BCGPToolbarFontCombo.inl"
#include "BCGPToolBarImages.inl"
#include "BCGPToolbarMenuButton.inl"
#include "BCGPToolbarMenuButtonsButton.inl"
#include "BCGPToolbarSpinEditBoxButton.inl"
#include "BCGPToolbarSystemMenuButton.inl"
#include "BCGPToolBox.inl"
#include "BCGPToolsPage.inl"
#include "BCGPToolTipCtrl.inl"
#include "BCGPTooltipManager.inl"
#include "BCGPURLLinkButton.inl"
#include "BCGPUserTool.inl"
#include "BCGPUserToolsManager.inl"
#include "BCGPWindowsManagerDlg.inl"
#include "BCGPWinXPVisualManager.inl"
#include "BCGPWnd.inl"
#include "BCGPWorkspace.inl"
#include "ButtonAppearanceDlg.inl"
#include "ButtonsList.inl"
#include "ButtonsTextList.inl"
#include "CalendarPopup.inl"
#include "CmdUsageCount.inl"
#include "ColorPage1.inl"
#include "ColorPage2.inl"
#include "ColorPopup.inl"
#include "CustomizeButton.inl"
#include "ImagePaintArea.inl"
#include "KeyAssign.inl"
#include "MenuHash.inl"
#include "MenuImages.inl"
#include "PropertySheetCtrl.inl"
#include "RegPath.inl"
#include "ToolbarNameDlg.inl"
#include "TrackMouse.inl"
#include "BCGCBPro.inl"
#endif



#include "BCGPControls/test_BCGPControls.inl"

int test_bcg()
{
  //sys_t sys[1] = {0};
  sys_t* sys = globalData.sys;
  CPage1 test_CPage1[1];
  psys = &sys;
  win_set(sys, test_CPage1->proc, test_CPage1, test_CPage1->c, 0, "test_CPage1", WT_WINDOWS, 0, 0, 0, 0, 0);
  //test_circles_t test_circles[1] = {0};
  //win_set(sys, test_aa_test_proc, test_aa_test, test_aa_test->c, 0, "test_aa_test", WT_WINDOWS, 0, 0, 0);

  for (;;) {
    int ch = waitkey(sys, -1);

    if (-2 == ch) {
      break;
    }

    //printf("--%08x\n", &ch);
  }

  sys_exit(sys);
  return 0;
}

#endif // _TEST_BCG_INL_
