//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RubixCube.rc
//
#define IDD_ABOUTBOX                    100
//#define IDR_MAINFRAME                   128
#define IDR_RUBIX0TYPE                  129
#define IDD_DIAG_CTRL                   130
#define IDD_DIAG_VIEW                   131
#define IDI_RUBIXCUBE                   133
#define IDD_DIAG_CMD                    134
#define IDR_AVITEST                     134
#define IDD_DIAG_INP                    135
#define IDD_DIAG_EXTR                   137
//#define IDB_BITMAP1                     139
#define IDD_DIAG_OUT                    141
#define IDC_RADIO_X                     1000
#define IDC_RADIO_Y                     1001
#define IDC_RADIO_Z                     1002
#define IDC_RADIO_P1                    1003
#define IDC_STAT_PRODUCT                1004
#define IDC_RADIO_P2                    1005
#define IDC_STAT_COPYRIGHT              1006
#define IDC_RADIO_P3                    1007
#define IDC_BUTTON_POS                  1008
#define IDC_BUTTON_NEG                  1009
#define IDD_TIMER                       1010
#define IDC_SLID_DISTANCE               1011
#define ID_RADIO_CUBE                   1012
#define IDC_RADIO_OBS                   1013
#define IDC_RADIO_DEFAULT               1014
#define IDC_EDT_CMD                     1015
#define IDC_CMD_ALL                     1016
#define IDC_RUN                         1017
#define IDC_STEP                        1018
#define IDC_RUNFAST                     1019
#define IDC_CMD_INIT                    1020
#define IDC_CMD_REV                     1021
#define IDC_CMD_ROT                     1022
#define IDC_CMD_M                       1023
#define IDC_CMD_L                       1024
#define IDC_CMD_LR                      1025
#define IDC_CMD_F                       1026
#define IDC_CMD_FR                      1027
#define IDC_CMD_B                       1028
#define IDC_CMD_BR                      1029
#define IDC_CMD_R                       1030
#define IDC_CMD_RR                      1031
#define IDC_CMD_U                       1032
#define IDC_CMD_UR                      1033
#define IDC_CMD_D                       1034
#define IDC_CMD_DR                      1035
#define IDC_CMDHELP                     1036
#define IDC_CMDDISPLAY                  1037
#define IDC_CMD_ORIGIN                  1038
#define IDC_CHKCOLOR0                   1039
#define IDC_CHKCOLOR1                   1040
#define IDC_CHKCOLOR2                   1041
#define IDC_CHKCOLOR3                   1042
#define IDC_CHKCOLOR4                   1043
#define IDC_CHKCOLOR5                   1044
#define IDC_BTN_U                       1045
#define IDC_BTN_D                       1046
#define IDC_BTN_L                       1047
#define IDC_BTN_R                       1048
#define IDC_BTN_F                       1049
#define IDC_BTN_B                       1050
#define IDC_RCINP                       1051
#define IDC_ANIMATE                     1052
#define IDC_DEFAULTCOLOR                1053
#define IDC_EXTRACT                     1054
#define IDC_CHKHISTORY                  1055
#define ID_ACQUIRE                      1057
#define IDC_OBTN_U                      1058
#define IDC_OBTN_D                      1059
#define IDC_OBTN_L                      1060
#define IDC_OBTN_R                      1061
#define IDC_OBTN_F                      1062
#define IDC_OBTN_B                      1063
#define IDC_BTN_ORIGINE                 1064
#define IDC_BUTTON1                     1065
#define IDC_EDIT                        1066
#define ID_CENTERS                      1067
#define ID_SOLVER                       1068
#define ID_OPTISOLVER                   1069
#define IDC_CENTERS                     32771
#define IDC_SOLVER                      32772
#define IDC_OPTISOLVER                  32773
#define ID_COMMAND                      32774
#define ID_COLERASE                     32775
#define ID_COLCOPY                      32776
#define ID_FACETCENT                    32777
#define ID_FACETEDGE                    32778
#define ID_FACETCORN                    32779
#define ID_CINIT                        32780
#define ID_FILE_SELECTSOURCE            32781
#define ID_VIEW                         32782
#define ID_UNDO                         32783
#define ID_ORIGIN                       32784
#define ID_TOOLTIPS_MODE                32785
#define ID_CUBE_RND                     32786
#define ID_CUBES_DUMP_00                32787
#define ID_CUBES_DUMP_01                32788
#define ID_CUBES_DUMP_02                32789
#define ID_CUBES_DUMP_03                32790
#define ID_CUBES_DUMP_04                32791
#define ID_CUBES_DUMP_05                32792
#define ID_CUBES_DUMP_06                32793
#define ID_CUBES_DUMP_07                32794
#define ID_CUBES_DUMP_08                32795
#define ID_CUBES_DUMP_09                32796
#define ID_CUBES_DUMP_10                32797
#define ID_FILE_ACQUIRE                 32798
#define ID_COMMANDTEXT                  32799
#define ID_CUBEP_RND                    32800
#define ID_CUBE_INP                     32801
#define ID_CUBE_INIT                    32802
#define ID_SHOWPLAN                     32803
#define ID_FILETIFF_OPEN                32804
#define ID_TEST                         32805
#define ID_FACE_R0                      32806
#define ID_FACE_R1                      32807
#define ID_FACE_R2                      32808
#define ID_FACE_R3                      32809
#define ID_TEST2                        32810
#define ID_COMMENTS                     32811

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
