//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by test.rc
//
#define IDD_TEST_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDD_DIALOG_DEVSTATIS            131
#define IDD_DIALOG_DEVSET               132
#define IDD_DIALOG_USER                 133
#define IDD_DIALOG_TIME_GROUP           135
#define IDD_DIALOG_RIGHT                136
#define IDI_WEEKCHECKSELECT             139
#define IDI_TIMEGROUP                   140
#define IDI_TIMEGROUPSELECT             141
#define IDI_WEEKCHECK                   142
#define IDI_RIGHT                       144
#define IDI_RIGHTSELECT                 145
#define IDD_DIALOG_UDLOAD               146
#define IDB_FOLDERS                     148
#define IDD_DIALOG_DSP_AUTH             149
#define IDD_DIALOG_USERGROUP            150
#define IDD_DIALOG_VIDEO                151
#define IDD_WebServiceMrg               152
#define IDD_CreateDynamicDlg            153
#define IDD_PassWordDlg                 154
#define IDC_BUTTON_SERCH                1001
#define IDC_BUTTON_CONNECT              1002
#define IDC_BUTTON_DISCONNECT           1003
#define IDC_BUTTON_CN                   1004
#define IDC_LIST_DEV                    1005
#define IDC_EDIT_TOTAL_USER             1006
#define IDC_LIST_USER                   1006
#define IDC_EDIT_NEW_USER               1007
#define IDC_BUTTON_DCN                  1007
#define IDC_EDIT_SYN_USER               1008
#define IDC_BUTTON_CN_UDISK             1008
#define IDC_EDIT_REC_DATE               1008
#define IDC_EDIT_NO_FEAT                1009
#define IDC_EDIT_TOTAL_REG              1010
#define IDC_EDIT_NEW_REG                1011
#define IDC_EDIT_FAILURE_REG            1012
#define IDC_BUTTON_UP                   1015
#define IDC_BUTTON_DOWN                 1016
#define IDC_CHECK_BASE_A                1018
#define IDC_CHECK_BASE_B                1019
#define IDC_CHECK_BASE_C                1020
#define IDC_CHECK_WG_A                  1021
#define IDC_CHECK_WG_B                  1022
#define IDC_CHECK_WG_C                  1023
#define IDC_EDIT_PASS                   1024
#define IDC_EDIT_CONTENT                1025
#define IDC_CHECK_BASE_D                1028
#define IDC_CHECK_BASE_E                1029
#define IDC_BUTTON_NEW                  1030
#define IDC_EDIT_ID                     1033
#define IDC_CHECK_BASE_F                1033
#define IDC_EDIT_CARD                   1034
#define IDC_EDIT_NAME                   1035
#define IDC_EDIT_DEP                    1036
#define IDC_EDIT_RIGHT                  1037
#define IDC_EDIT_TYPE                   1038
#define IDC_BUTTON_SAVE                 1039
#define IDC_BUTTON_CANCEL               1040
#define IDC_EDIT_CHANGEID               1041
#define IDC_EDIT_INVALIDETIME           1042
#define IDC_CHECK_PIC                   1043
#define IDC_CHECK_FEAT                  1044
#define IDC_COMBO_CONDITION             1045
#define IDC_STATIC_PIC                  1047
#define IDC_BUTTON_DEL                  1048
#define IDC_CHECK_LOCAL                 1049
#define IDC_CHECK_DSP                   1050
#define IDC_BUTTON_PIC                  1051
#define IDC_BUTTON1                     1052
#define IDC_OkBnt                       1052
#define IDC_BNTWEB                      1052
#define IDC_LIST_RECORD                 1053
#define IDC_BUTTON_VIDEO2               1053
#define IDC_CancelBnt                   1053
#define IDC_LIST_LOG                    1054
#define IDC_BUTTON_VIDEO3               1054
#define IDC_CHECK_BLACK                 1055
#define IDC_LIST_IMAGE                  1055
#define IDC_BUTTON_VIDEO4               1055
#define IDC_STATIC_RECORD_PIC           1056
#define IDC_CHECK_MUTEX                 1056
#define IDC_BUTTON_VIDEO6               1056
#define IDC_CHECK_RECORD_PIC            1057
#define IDC_BUTTON_VIDEO5               1057
#define IDC_COMBO_RECORD                1058
#define IDC_BUTTON_DLRECORD             1059
#define IDC_BUTTON_DELRECORD            1060
#define IDC_BUTTON_DL_LOG               1061
#define IDC_DATETIME_START_REC          1062
#define IDC_DATETIME_END_REC            1063
#define IDC_DATETIME_START_USER         1064
#define IDC_DATETIME_END_USER           1065
#define IDC_BUTTON_TIMEGROUP            1066
#define IDC_BUTTON_RRIGHT               1067
#define IDC_BUTTON_DELETE               1068
#define IDC_BUTTON_DEL_LOG              1068
#define IDC_BUTTON_UPLOAD               1069
#define IDC_BUTTON_DL_IMAGE             1069
#define IDC_BUTTON_DEL_IMAGE            1070
#define IDC_TREE_TIMEGROUP              1071
#define IDC_TREE_WEEK                   1072
#define IDC_DATETIMEPICKER_START        1077
#define IDC_DATETIMEPICKER_END          1079
#define IDC_CHECK_YEAR                  1083
#define IDC_CHECK_MONTH                 1084
#define IDC_CHECK_DAY                   1085
#define IDC_CHECK_WEEK                  1086
#define IDC_CHECK_HOLIDY_VALIDATE       1090
#define IDC_LIST_TIMEGROUP              1092
#define IDC_TREE_RIGHT                  1093
#define IDC_LIST_TG                     1094
#define IDC_BUTTON_DOWNLOAD             1095
#define IDC_COMBO_RIGHT                 1096
#define IDC_RADIO_SUPERADMIN            1097
#define IDC_RADIO_ADMIN                 1098
#define IDC_RADIO_NOMAL                 1099
#define IDC_BUTTON_OPEN_DOOR            1100
#define IDC_CHECK_BASE_G                1101
#define IDC_CHECK_INPUT_A               1102
#define IDC_CHECK_INPUT_B               1103
#define IDC_BUTTON_EDIT                 1104
#define IDC_IPADDRESS_ADDR              1105
#define IDC_BUTTON_SETADDR              1106
#define IDC_IPADDRESS_ADDR2             1107
#define IDC_RADIO_MODE_A                1108
#define IDC_IPADDRESS_S                 1108
#define IDC_RADIO_MODE_B                1109
#define IDC_RADIO_MODE_C                1110
#define IDC_RADIO_ALL                   1118
#define IDC_CHECK_WG_D                  1120
#define IDC_RADIO_LOG_ID                1120
#define IDC_BUTTON_UPDATE               1121
#define IDC_EDIT_FILE                   1122
#define IDC_BUTTON_FILE                 1123
#define IDC_RADIO_NO_RIGHT              1124
#define IDC_RADIO_SINGLE_RIGHT          1125
#define IDC_EDIT_USER                   1126
#define IDC_EDIT_PWS                    1127
#define IDC_EDIT_S_HOUR                 1130
#define IDC_EDIT_S_MINI                 1131
#define IDC_EDIT_S_SECOND               1132
#define IDC_EDIT_E_HOUR                 1133
#define IDC_EDIT_E_MINI                 1134
#define IDC_EDIT_E_SECOND               1135
#define IDC_CHECK_TIME                  1136
#define IDC_CHECK_HOLIDY                1137
#define IDC_CHECK_A                     1138
#define IDC_CHECK_B                     1139
#define IDC_CHECK_D                     1141
#define IDC_CHECK_E                     1142
#define IDC_CHECK_F                     1143
#define IDC_CHECK_G                     1144
#define IDC_CHECK_H                     1145
#define IDC_CHECK_I                     1146
#define IDC_CHECK_C                     1147
#define IDC_EDIT_MANEGET                1148
#define IDC_EDIT_LOCK                   1149
#define IDC_EDIT_PWD                    1150
#define IDC_EDIT_TOTAL_ALARM            1156
#define IDC_EDIT_TOTAL_LOG              1157
#define IDC_EDIT_TOTAL_IMAGE            1158
#define IDC_COMBO_UG                    1159
#define IDC_CHECK_MANEGT                1160
#define IDC_CHECK_OUT                   1161
#define IDC_CHECK_ORDER                 1164
#define IDC_EDIT_N                      1166
#define IDC_LIST_SEL_USER               1167
#define IDC_EDIT_F                      1168
#define IDC_BUTTON_R                    1169
#define IDC_BUTTON_L                    1170
#define IDC_TREE_LIST                   1171
#define IDC_BUTTON_UG                   1172
#define IDC_COMBO_VALIDE                1177
#define IDC_CHECK_OPEN_A                1178
#define IDC_CHECK_OPEN_B                1179
#define IDC_CHECK_OPEN_C                1180
#define IDC_RADIO_ALL_IMAGE             1181
#define IDC_RADIO_IMAGE_ID              1183
#define IDC_EDIT_COUNT                  1184
#define IDC_RADIO_NET                   1187
#define IDC_RADIO_UDISK                 1188
#define IDC_EDIT_UPATH                  1189
#define IDC_BUTTON_UPATH                1190
#define IDC_BUTTON_CANCLE               1192
#define IDC_BUTTON_REMOTE               1193
#define IDC_BUTTON_R_CLOSE              1195
#define IDC_CHECK_CARD_INVALIDE         1196
#define IDC_BUTTON_NOMAL                1197
#define IDC_CHECK_IDLINE                1198
#define IDC_STATIC_VIDEO2               1202
#define IDC_LIST_IP                     1203
#define IDC_STATIC_VIDEO1               1206
#define IDC_BUTTON_VIDEO1               1207
#define IDC_STATIC_VIDEO3               1208
#define IDC_BUTTON_VIDEO                1208
#define IDC_STATIC_VIDEO4               1209
#define IDC_BUTTON_CAP                  1209
#define IDC_STATIC_VIDEO5               1210
#define IDC_EDIT_ID_USER                1210
#define IDC_STATIC_VIDEO6               1211
#define IDC_CHECK_USER_EX               1211
#define IDC_CHECK_TEXT                  1212
#define IDC_EDIT_FEAT                   1213
#define IDC_EDIT_PIC                    1214
#define IDC_CHECK_J                     1214
#define IDC_BUTTON_REBOOT               1215
#define IDC_WebURL1Edt                  1216
#define IDC_LoadChk                     1217
#define IDC_WriteRecord                 1218
#define IDC_WriteUserChk                1219
#define IDC_SyncTimeChk                 1220
#define IDC_WebURL1Edt2                 1221
#define IDC_LoadChk2                    1222
#define IDC_WriteRecord2                1223
#define IDC_WriteUserChk2               1224
#define IDC_SyncTimeChk2                1225
#define IDC_ServiceVerifyChk            1226
#define IDC_IPAdr                       1227
#define IDC_GateWay                     1228
#define IDC_TIMEPWD                     1228
#define IDC_MulitIP                     1229
#define IDC_STDD                        1229
#define IDC_SubMask                     1230
#define IDC_CHECK1                      1230
#define IDC_DnsIPs                      1231
#define IDC_DATETIMEPICKER1             1231
#define IDC_DATETIMEPICKER2             1232
#define IDC_OnlyUpLoadTextChk           1232
#define IDC_EnaleWebServiceChk          1233
#define IDC_ServiceVerifyChk2           1234
#define IDC_EDIT2                       1235
#define IDC_OnlyUpLoadTextChk2          1235
#define IDC_EDIT1                       1236
#define IDC_EnaleWebServiceChk2         1236
#define IDM_DEVSTATIS                   32771
#define IDM_DEVSET                      32772
#define IDR_MENU_SYN_TIME               32773
#define IDR_TIMEGROUP                   32774
#define IDR_RIGHT                       32775
#define IDR_DEVCUT                      32776
#define IDR_DEV_FORMAT                  32777
#define IDR_DEVAUTH                     32778
#define IDR_UGROUP                      32779
#define IDM_NETWORKSET                  32780
#define IDR_DMYPWD                      32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1237
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
