
#define LAYER_DECLARATION(NAME, xx)  extern Layer* NAME ## _ ## xx();  Layer* (*NAME ## _ptr )() = NAME ## _ ## xx;

#ifdef __arm__
LAYER_DECLARATION(AbsVal, arm_layer_creator)
LAYER_DECLARATION(BatchNorm, arm_layer_creator)
LAYER_DECLARATION(Bias, arm_layer_creator)
LAYER_DECLARATION(Convolution, arm_layer_creator)
LAYER_DECLARATION(Deconvolution, arm_layer_creator)
LAYER_DECLARATION(Eltwise, arm_layer_creator)
LAYER_DECLARATION(InnerProduct, arm_layer_creator)
LAYER_DECLARATION(LRN, arm_layer_creator)
LAYER_DECLARATION(Pooling, arm_layer_creator)
LAYER_DECLARATION(PReLU, arm_layer_creator)
LAYER_DECLARATION(ReLU, arm_layer_creator)
LAYER_DECLARATION(Scale, arm_layer_creator)
LAYER_DECLARATION(Sigmoid, arm_layer_creator)
LAYER_DECLARATION(Slice, arm_layer_creator)
LAYER_DECLARATION(Softmax, arm_layer_creator)
#else
LAYER_DECLARATION(AbsVal, layer_creator)
LAYER_DECLARATION(BatchNorm, layer_creator)
LAYER_DECLARATION(Bias, layer_creator)
LAYER_DECLARATION(Convolution, x86_layer_creator)
LAYER_DECLARATION(Deconvolution, layer_creator)
LAYER_DECLARATION(Eltwise, layer_creator)
LAYER_DECLARATION(InnerProduct, layer_creator)
LAYER_DECLARATION(LRN, layer_creator)
LAYER_DECLARATION(Pooling, layer_creator)
LAYER_DECLARATION(PReLU, layer_creator)
LAYER_DECLARATION(ReLU, layer_creator)
LAYER_DECLARATION(Scale, layer_creator)
LAYER_DECLARATION(Sigmoid, layer_creator)
LAYER_DECLARATION(Slice, layer_creator)
LAYER_DECLARATION(Softmax, layer_creator)
#endif
LAYER_DECLARATION(Concat, layer_creator)
LAYER_DECLARATION(BNLL, layer_creator)
LAYER_DECLARATION(Crop, layer_creator)
LAYER_DECLARATION(Dropout, layer_creator)
LAYER_DECLARATION(ELU, layer_creator)
LAYER_DECLARATION(Exp, layer_creator)
LAYER_DECLARATION(Flatten, layer_creator)
LAYER_DECLARATION(Input, layer_creator)
LAYER_DECLARATION(Log, layer_creator)
LAYER_DECLARATION(MVN, layer_creator)
LAYER_DECLARATION(Power, layer_creator)
LAYER_DECLARATION(Split, layer_creator)
LAYER_DECLARATION(TanH, layer_creator)
LAYER_DECLARATION(Threshold, layer_creator)