
struct test_case test_case_set[]={
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUV420,
.disp_format = DISP_FORMAT_YUV420,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 328,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 248,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 312,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 232,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 648,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 488,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 632,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 472,
.csi_format   = V4L2_PIX_FMT_YUV422P,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUV420,
.disp_format = DISP_FORMAT_YUV420,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_NV16,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_UV_COMBINED,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_NV12,
.disp_format = DISP_FORMAT_YUV420,
.disp_mode  = DISP_MOD_NON_MB_UV_COMBINED,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUV420,
.disp_format = DISP_FORMAT_YUV420,
.disp_mode  = DISP_MOD_NON_MB_PLANAR,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_NV16,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_NON_MB_UV_COMBINED,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_NV12,
.disp_format = DISP_FORMAT_YUV420,
.disp_mode  = DISP_MOD_NON_MB_UV_COMBINED,
.disp_seq   = DISP_SEQ_UVUV,
},
{
.input_width  = 320,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 328,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 320,
.input_height = 248,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 312,
.input_height = 240,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 320,
.input_height = 232,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 648,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 640,
.input_height = 488,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 632,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 640,
.input_height = 472,
.csi_format   = V4L2_PIX_FMT_YUYV,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YUYV,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_YVYU,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_YVYU,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_UYVY,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_UYVY,
},
{
.input_width  = 640,
.input_height = 480,
.csi_format   = V4L2_PIX_FMT_VYUY,
.disp_format = DISP_FORMAT_YUV422,
.disp_mode  = DISP_MOD_INTERLEAVED,
.disp_seq   = DISP_SEQ_VYUY,
},
};

enum v4l2_ctrl_type qc_ctrl[]=
{
  V4L2_CID_BRIGHTNESS,
    V4L2_CID_CONTRAST,
    V4L2_CID_SATURATION,
    V4L2_CID_HUE,
    V4L2_CID_VFLIP,
    V4L2_CID_HFLIP,
    V4L2_CID_GAIN,
    V4L2_CID_AUTOGAIN,
    V4L2_CID_EXPOSURE,
    V4L2_CID_EXPOSURE_AUTO,
    V4L2_CID_DO_WHITE_BALANCE,
    V4L2_CID_AUTO_WHITE_BALANCE,
    (V4L2_CID_BASE+31)
};
