# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: universal_report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='universal_report.proto',
  package='rongyi.report',
  syntax='proto2',
  serialized_pb=_b('\n\x16universal_report.proto\x12\rrongyi.report\"v\n\x16UniversalReportRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x14\n\x0cmessage_name\x18\x03 \x01(\t\x12\x14\n\x0cmessage_data\x18\x04 \x03(\x0c\x12\x11\n\tcheck_sum\x18\x05 \x03(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UNIVERSALREPORTREQUEST = _descriptor.Descriptor(
  name='UniversalReportRequest',
  full_name='rongyi.report.UniversalReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rongyi.report.UniversalReportRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rongyi.report.UniversalReportRequest.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_name', full_name='rongyi.report.UniversalReportRequest.message_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_data', full_name='rongyi.report.UniversalReportRequest.message_data', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='check_sum', full_name='rongyi.report.UniversalReportRequest.check_sum', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['UniversalReportRequest'] = _UNIVERSALREPORTREQUEST

UniversalReportRequest = _reflection.GeneratedProtocolMessageType('UniversalReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNIVERSALREPORTREQUEST,
  __module__ = 'universal_report_pb2'
  # @@protoc_insertion_point(class_scope:rongyi.report.UniversalReportRequest)
  ))
_sym_db.RegisterMessage(UniversalReportRequest)


# @@protoc_insertion_point(module_scope)
