// Copyright (C) 2002-2012 Nikolaus Gebhardt
// This file is part of the "Irrlicht Engine".
// For conditions of distribution and use, see copyright notice in irrlicht.h
#ifndef __I_RANDOMIZER_H_INCLUDED__
#define __I_RANDOMIZER_H_INCLUDED__
//! Interface for generating random numbers
class IRandomizer
{
public:
  //! resets the randomizer
  /** \param value Initialization value (seed) */
  void reset(s32 value = 0x0f0f0f0f) = 0;
  //! generates a pseudo random number in the range 0..randMax()
  s32 rand() = 0;
  //! generates a pseudo random number in the range 0..1
  f32 frand() = 0;
  //! get maxmimum number generated by rand()
  s32 randMax() = 0;
};
#endif

